language: go
go:
  - 1.12
cache:
  directories:
    - vendor
install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0
script:
  - golangci-lint run
  - go build workplace-incoming-hook.go