language: go
go:
  - 1.12
cache:
  directories:
    - vendor
install:
  - make install
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0
script:
  - make lint
  - make build